sudo: required
dist: trusty

stages:
  - test
  - deploy

language: node_js
node_js: 8

cache:
  directories:
    - $HOME/haxe

os:
  - linux
  # - osx

env:
  # - HAXE_VERSION=3.4.7
  - HAXE_VERSION=nightly
  
before_install:
  # install python 3.5
  - sudo add-apt-repository -y ppa:fkrull/deadsnakes
  - sudo apt-get update
  - sudo apt-get install python3.5
  - sudo apt-get install python3.5-dev
  - sudo apt-get install libncurses5-dev
  - sudo ln -sf /usr/bin/python3.5 /usr/bin/python3
    
install:
  - npm i -g lix
  - lix install haxe $HAXE_VERSION
  - lix download
  
script:
  - lix run travix java
  - lix run travix node -lib embed-js
  - lix run travix node
  - lix run travix python

# jobs:
#   include:
#     # - stage: test # should uncomment this when there is no matrix above (e.g. only one os, one env, etc)
#     - stage: deploy
#       os: linux
#       install:
#         - npm i -g lix
#         - lix download
#       script: skip
#       env:
#         secure: xxxx
#       after_success:
#         - lix run travix install
#         - lix run travix release
